### ISSUE TITLE
Pawn Move Invalid but Turn Changes

### ISSUE THREAD

**Issue by CalebStadler** [nwestervelt/chess-game#15]
When a pawn moves forward but not a legal move and not through any pieces or on top of pieces, the invalid move exception does not occur which allow for the turn to change. Pawn still goes back to original spot though.

**Comment by nwestervelt** [comment]
I forgot about the bug about the pawn not throwing the invalid move exception.

At the time I discovered it, we weren't depending on the invalid move exception to prevent some other operation from occurring, so I left it alone.

We can either leave this issue to be resolve later, or work on it before our next meeting with Dr. Sun. I'll look into the bug if I still have free time after I complete implementing everything I need to for checking if the King is in check and checkmate.

**Comment by nwestervelt** [comment]
Fixed with commit 192db13a60eb56cd9b6001b83680e6ec95926a4b.
