### ISSUE TITLE
Checkmate Window not Popping up

### ISSUE THREAD

**Issue by CalebStadler** [nwestervelt/chess-game#23]
The checkmate window does not pop up in this move order when it should. It comes up after the black king tries to make a move. 
Move order: 
1.   g3        e5
2.   Bh3        d5
3.   d4        e4
4.   Bg5        Qxg5
5.   Bxc8        f5
6.   Bxb7        f4
7.   Bxa8        fxg3
8.   hxg3        Nf6
9.   Nh3        Qf5
10.   Nc3        Bb4
11.   Nf4        0-0
12.   Nxd5        Nxd5
13.   Bxd5+        Qxd5
14.   a3        Qf5
15.   axb4        Qxf2+
16.   Kd2        e3+
17.   Kd3        Nc6
18.   Rh5        Nxb4+
19.   Ke4        Qf4

**Comment by nwestervelt** [comment]
The white King is actually not in check mate after this move sequence, but the checkmate window shouldn't be displaying when the White king attempts to move without getting out of check.

**Comment by nwestervelt** [comment]
Fixed with commit c9d76f8d6f0277845a12708ed479aecab5af3733.
